### PR TITLE
Testing inside dwg

### PR DESCRIPTION
**Pull request by phliberato**
I created new functions to testing existing DWG and a new DWG.

### CODE REVIEW

**Comment by CADbloke** [comment]
Cheers Phil, I'll take a look at this soon when I get a chance (not tonight, I have a leave-pass for :beer: club).

I see my preference for 2x spaces indentation is haunting me already. I need to rethink that.

**Comment by phliberato** [comment]
```
Issue #11 fixed!
```

**Comment by CADbloke** [comment]
Hi Phil,
Sorry I didn't get to this on the weekend, I was too tired to do it justice. I had a quick look at it and it looks great. I will endeavour to get it merged in soon. Thanks for your valuable efforts and feedback.

**Comment by CADbloke** [comment]
Merged most of this and it was good. Thank you.

https://github.com/CADbloke/CADtest/commit/57fdaed016d602f6332fb64abe35b39836e1171f

**Comment by CADbloke** [comment]
It wasn't a clean merge because I mucked around a bit - also added proper .gitignore files and deleted your .suo file.

**Pull request closed without merging**
